name: ci

on: [push]

jobs:
  tests:
    name: ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
        os: ["ubuntu-18.04", "macos-10.15", "windows-2019"]
        python-version: ["3.6"]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.5.0
        with:
          auto-update-conda: true
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
      - name: install mpi4py
        if: runner.os != 'Windows'
        shell: bash -l {0}
        # no mpi4py package in conda-forge for windows
        run: conda install -c conda-forge mpi4py=3.0.3
      - name: install baselines
        shell: bash -l {0}
        run: pip install https://github.com/openai/baselines/archive/9ee399f5b20cd70ac0a871927a6cf043b478193f.zip
      - name: Test with pytest
        shell: bash -l {0}
        run: pytest
      # - name: Build and publish
      #   # env:
      #     # TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     # TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     python setup.py sdist bdist_wheel
      #     echo twine upload dist/*
